apiVersion: v1
kind: Pod
metadata:
  name: entrademo-pod
  labels:
    azure.workload.identity/use: "true"  # Required. Only pods with this label can use workload identity.
spec:
  serviceAccountName: workload-identity-sa
  containers:
  - name: entrademo-container
    image: aaddemoacr.azurecr.io/connect-from-aks-demo:latest

    imagePullPolicy: Always
    command: ["dotnet", "ConnectFromAKS.dll"] 
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m"
    env:
         - name: AUTHENTICATION_TYPE
           value: "WORKLOAD_IDENTITY" # change to ACCESS_KEY to authenticate using access key
         - name: REDIS_HOSTNAME
           value: "your redis hostname"
         - name: REDIS_ACCESSKEY
           value: "your access key" 
         - name: REDIS_PORT
           value: "6380" 
  restartPolicy: Never