apiVersion: v1
kind: Pod
metadata:
  name: entrademo-pod
  labels:
    azure.workload.identity/use: "true"  # Required. Only pods with this label can use workload identity.
spec:
  serviceAccountName: workload-identity-sa
  containers:
  - name: entrademo-container
    image: youracr.azurecr.io/connect-from-aks-sample:1.0
    imagePullPolicy: Always
    command: ["dotnet", "ConnectFromAKS.dll"] 
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m"
    env:
         - name: CONNECTION_OPTION
           value: "ACCESS_KEY" #"MANAGED_IDENTITY"
         - name: CONNECTION_STRING
           value: "your connection string" 
         - name: CACHE_HOSTNAME
           value: "yourcachename.redis.cache.windows.net"
  restartPolicy: Never